version: '2'

services:
    db:
        image: postgres
        container_name: mydb
    php:
        build:
            context: php7-fpm
            args:
                TIMEZONE: ${TIMEZONE}
        volumes:
            - ${SYMFONY_APP_PATH}:/var/www/symfony
            - ./logs/symfony:/var/www/symfony/app/logs
    nginx:
        build: nginx
        ports:
            - 3001:80
        volumes_from:
            - php
        volumes:
            - ./logs/nginx/:/var/log/nginx
        container_name: imiebook

    elasticsearch:
        image: elasticsearch
        container_name: elastic
        ports:
            - 9200:9200
