version: 2

general:
  branches:
    only:
     - egt_circleci
jobs:
  build:
    machine:
      image: circleci/classic:201708-01

    steps:
      - checkout

      - run:
          name: BuildApplication
          command: docker-compose build
