version: 2

general:
    branches:
        only:
            - egt_circleci
jobs:
    build:
        machine:
            image: circleci/classic:latest

        steps:
            - checkout

            - run:
                  name: BuildApplication
                  command: |
                    docker-compose build
                    docker-compose up -d

            - run:
                  name: Init Symfony
                  command: |
                    docker-compose run php bash "composer install"
                    

            - run:
                name: Test curl login
                command: |
                    curl -X POST http://127.0.0.1:3001/app_dev.php/login_check -d _username=test@test.fr -d _password=p@ssword
