version: 2

general:
    branches:
        only:
            - egt_circleci
jobs:
    build:
        machine:
            image: circleci/classic:latest

        steps:
            - checkout

            - run:
                  name: BuildApplication
                  command: |
                    docker-compose build
                    docker-compose up -d
                    docker-compose exec php bash

            - run:
                  name: Init Symfony
                  command: |
                    composer install
                    php bin/console  doctrine:database:create
                    php bin/console  doctrine:schema:update --force
                    php bin/console doctrine:fixtures:load
                    php bin/console cache:clear
                    HTTPDUSER=`ps axo user,comm | grep -E '[a]pache|[h]ttpd|[_]www|[w]ww-data|[n]ginx' | grep -v root | head -1 | cut -d\  -f1`
                    setfacl -R -m u:$HTTPDUSER:rwX -m u:`whoami`:rwX var
                    setfacl -dR -m u:$HTTPDUSER:rwX -m u:`whoami`:rwX var
                    mkdir -p var/jwt
                    openssl genrsa -passout pass:imie -out var/jwt/private.pem -aes256 4096
                    openssl rsa passin pass:imie -pubout -in var/jwt/private.pem -out var/jwt/public.pem
                    rm /app/config/parameters.yml
                    mv /app/config/parameters.yml.dist /app/config/parameters.yml

            - run:
                name: Test curl login
                command: |
                    curl -X POST http://127.0.0.1:3001/app_dev.php/login_check -d _username=test@test.fr -d _password=p@ssword
