version: 2

general:
    branches:
        only:
            - develop
            - master
jobs:
    build:
        machine:
            image: circleci/classic:latest

        steps:
            - checkout

            - run:
                  name: Construct Containers
                  command: |
                    docker-compose build
                    docker-compose up -d

            - run:
                  name: Init Symfony
                  command: |
                    docker-compose exec php cp app/config/parameters.yml.dist app/config/parameters.yml
                    docker-compose exec php composer install
                    docker-compose exec php bin/console  doctrine:database:create
                    docker-compose exec php bin/console  doctrine:schema:update --force
                    docker-compose exec php bin/console doctrine:fixtures:load -n
                    docker-compose exec php bin/console cache:clear
                    docker-compose exec php chown -R www-data var
                    docker-compose exec php mkdir -p var/jwt
                    docker-compose exec php openssl genrsa -passout pass:imie -out var/jwt/private.pem -aes256 4096
                    docker-compose exec php openssl rsa -passin pass:imie -pubout -in var/jwt/private.pem -out var/jwt/public.pem

            - run:
                name: Test PHPUnit
                command: |
                    docker-compose exec php vendor/bin/phpunit
