version: 2

general:
  branches:
    only:
     - egt_circleci
jobs:
  build:
    steps:
      - checkout

      - setup_remote_docker


      - run:
          name: BuildApplication
          command: docker-compose build
