version: 2

general:
  branches:
    only:
     - egt_circleci
jobs:
  build:
    docker:
      - image: debian:stretch
    steps:
      - checkout
      - run:
          name: BuildApplication
          command: docker-compose build
