# app/config/config.yml
fos_rest:
    routing_loader:
        include_format: false
    view:
        view_response_listener: true
    format_listener:
        rules:
            - { path: '^/', priorities: ['json'], fallback_format: 'json' }

fos_user:
    db_driver: orm
    firewall_name: main
    user_class: AppBundle\Entity\Users
    service:
        mailer: fos_user.mailer.twig_swift
    from_email:
        address: "%mailer_user%"
        sender_name: "Imie Book"

fos_elastica:
    clients:
        default: { host: elastic, port: 9200 }
    indexes:
        app:
            client: default
            types:

                user:
                    properties:
                        surname: ~
                        lastname: ~
                        email: ~
                    persistence:
                        # the driver can be orm, mongodb or phpcr
                        driver: orm
                        model: AppBundle\Entity\Users
                        provider: ~
                        finder: ~

                experiences:
                    properties:
                        enterprise: ~
                    persistence:
                        # the driver can be orm, mongodb or phpcr
                        driver: orm
                        model: AppBundle\Entity\Experiences
                        provider: ~
                        finder: ~

                degres:
                    properties:
                        enterprise: ~
                    persistence:
                        # the driver can be orm, mongodb or phpcr
                        driver: orm
                        model: AppBundle\Entity\Degres
                        provider: ~
                        finder: ~
