# app/config/config.yml
fos_rest:
    routing_loader:
        include_format: false
    view:
        view_response_listener: true
    format_listener:
        rules:
            - { path: '^/', priorities: ['json'], fallback_format: 'json' }

fos_user:
    db_driver: orm
    firewall_name: main
    user_class: AppBundle\Entity\Users
    service:
        mailer: fos_user.mailer.twig_swift
    from_email:
        address: "%mailer_user%"
        sender_name: "Imie Book"
    resetting:
        token_ttl: 0
        email:
            template:   email/password_resetting.email.twig
            from_email:
                address: "%mailer_user%"
                sender_name: "Imie Book - Demo Resetting"
