<?php
namespace AppBundle\Repository;

/**
 * DegresRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DegresRepository extends \Doctrine\ORM\EntityRepository
{

}
