<?php
namespace AppBundle\Repository;

use AppBundle\Model\SearchModel;

use Elastica\Query\BoolQuery;
use Elastica\Query\Terms;
use Elastica\Query;

/**
 * UsersRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UsersRepository extends \Doctrine\ORM\EntityRepository
{

    public function search(SearchModel $data, $finder) {
        // filter : skills, city, enterprise
        // label : name, surname, title (degres or experiences)
        // $finder = $this->container->get('fos_elastica.finder.app.user');

        $results = $finder->find($data->getLabel());
        return $results;
    }

}
