app:
    resource: '@AppBundle/Controller/'
    type: annotation

users:
    type:     rest
    resource: AppBundle\Controller\UsersController

# app/config/routing.yml
fos_user:
    type:     rest
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
